export const rooms = [
  {
    indx: 5,
    color: '#FF5757',
    h: 'Люкс',
    p: 'С дополнительной системой кондиционирования',
    max: 2,
    imgs: [
      require('../img/cabins/luxe3.jpg'),
      require('../img/cabins/luxe4.jpg'),
      require('../img/cabins/luxe5.jpg'),
      require('../img/cabins/luxe6.jpg'),
      require('../img/cabins/luxe1.jpg'),
      require('../img/cabins/luxe2.jpg'),
    ],
  },
  {
    indx: 4,
    color: '#7FFF6A',
    h: 'Полулюкс',
    p: 'С дополнительной системой кондиционирования',
    max: 2,
    imgs: [require('../img/cabins/deluxe3.jpg'), require('../img/cabins/deluxe1.jpg'), require('../img/cabins/deluxe2.jpg')],
  },
  {
    indx: 4,
    color: '#27E3C2',
    h: 'Полулюкс',
    p: 'С дополнительной системой кондиционирования',
    p1: 'С дополнительным местом',
    max: 2,
    imgs: [require('../img/cabins/deluxe3.jpg'), require('../img/cabins/deluxe1.jpg'), require('../img/cabins/deluxe2.jpg')],
  },
  {
    indx: 3,
    color: '#EEC1EE',
    h: '1-местная каюта',
    p: 'С дополнительным местом',
    max: 1,
    imgs: [require('../img/cabins/odnomestnaya3.jpg'), require('../img/cabins/odnomestnaya1.jpg'), require('../img/cabins/odnomestnaya2.jpg')],
  },
  {
    indx: 2,
    color: '#F1C84C',
    h: '2-местная каюта',
    p: 'С дополнительной системой кондиционирования',
    max: 2,
    imgs: [require('../img/cabins/odnomestnaya3.jpg'), require('../img/cabins/odnomestnaya1.jpg'), require('../img/cabins/odnomestnaya2.jpg')],
  },
  {
    indx: 1,
    color: '#8BF8FF',
    h: '3-местная каюта',
    max: 3,
    imgs: [require('../img/cabins/triple1.jpg'), require('../img/cabins/triple2.jpg')],
  },
  {
    indx: 0,
    color: '#FFA500',
    h: '4-местная каюта',
    max: 4,
    imgs: [require('../img/cabins/chetyrehmenstnaya1.jpg'), require('../img/cabins/chetyrehmenstnaya2.jpg')],
  },
  { indx: -1, color: 'gray', h: 'Забронированно' },
]
